let techKaro = {
    about: {
        programName: "Tech Karo",
        discription: "web-dev course",
        about: "TechKaro is an 8 months' Web Development Course, offered by CIRCLE Women Pakistan and sponsored by Engro Vopak. The course is aimed at talented but underserved youth of Pakistan. Our goal is to empower women in technology and help them generate income through their Web Developement skills.",
        duration: "8 months",
        fees: 500,
        leadBy: "Circle",
        founder: "Miss Sadaf Abid",
        instructor: "Miss Sarah Ahmed",
        courses: ["html", "CSS", "javascript"],
        institude: "Usman institude of technology",
        location: "ST-13 Abul Hasan Isphahani Rd, Block 7 Gulshan-e-Iqbal, Karachi, Karachi City",
        contact: "021-453768",
        email: "",
        website: "",
        numberOfTeacher: 1,
        numberOfStudents: 100,
        NumberOfEmployess: 20,
        sponcers: {
            sponser1: "Engro Vopak",
            aboutSponser: "",
            email: "",
            contactNumebr: 021,
            loctaion: "",
            amount: "500000",
        }
    },
    facilities: {
        transport: {
            isProvidingTransport: "true",
            collabotationWith: "Creem",
            discountPerRide: "50%",
        },
        labs: {
            isProvidingLAbs: "true",
            location: "Usman Institude",
            numberOfLAbs: 4,
            names: ["cl1", "cl2", "cl4", "fyp lab"],
            isProvidingAirConditionerFacilities: "true",
            isProvidingCleanEnvironment: "true",
            numbersOfComputersPerLab: 80,
            isProvidingInternet: "true",
            isProvidingLAbAssistant: "true",
            numberOfLAbAssistantPerLAb: 2,
            discriptionOfLAbAssistants: [{
                labAssistant1: "ali",
                gender: "male",
                contact: 0335 - 6789387,
                email: "",
                numOfhoursOfAvailibility: 4,
            }, {
                labAssistant2: "faizan",
                gender: "male",
                contact: 0335 - 67267927,
                email: "",
                numOfhoursOfAvailibility: 4,
            }],
            isprovidingChairs:"true",
            numberOfChairsPerClass:70,
            isprovidingTables:"true",
            numberOfChairsPerClass:30,
        },
        notebooks: {
            isProvidingNotebooks: "true",
            givenBy: "Engro Vopek",
            numberOfNotebooksPerStudents: 1,
        }


    },
    employes: {
        employ1: "teacher",
        numberOfTeacher: 1,
        discriptionOfTeacher: {
            name: "Sarah Ahmed",
            contactNumber: "0345778912",
            email: "",
            dateOfBirth: 12,
            cnic: 42401 - 4,
            address: "",
            githubUrl: "",
            qualification: "",
            university: "",
            faculty: "",
            yearOfPassedOut: 1,
            haseExperience: "true",
            NumOfYearsOfExperience: 2,
            meritalState: "single",
            skills: [],
            salary: 0000,
            hasAnyOtherJob: "true",
            OtherJob: "Free Launcer",
            certification: [],
            awards: [],
        },
        employ2: "Program Manager",
        numberOfProgramMAnagers: 2,
        discriptionsOfProgramMAnagers: [
            {
                programManager1: "Tuba Mohsin",
                position: "manager",
                contactNumber: "034567812",
                email: "",
                dateOfBirth: 12,
                cnic: 42401 - 4,
                address: "",
                qualification: "",
                university: "",
                faculty: "",
                yearOfPassedOut: 1,
                haseExperience: "true",
                NumOfYearsOfExperience: 2,
                meritalState: "single",
                skills: [],
                salary: 0000,
                hasAnyOtherJob: "true",
                OtherJob: "",
                certification: [],
                awards: [],
            }, {
                programManager2: "",
                position: "Manager",
                contactNumber: "0345778912",
                email: "",
                dateOfBirth: 12,
                cnic: 42401 - 4,
                address: "",
                qualification: "",
                university: "",
                faculty: "",
                yearOfPassedOut: 1,
                haseExperience: "true",
                NumOfYearsOfExperience: 2,
                meritalState: "single",
                skills: [],
                salary: 0000,
                hasAnyOtherJob: "true",
                OtherJob: "",
                certification: [],
                awards: [],
            },

        ],
        employ3: "embassaders",
        numberOfEmbassaders: 10,
        discriptionsOfEmbassadors: [
            {
                embassader1: "",
                position: "embassader",
                contactNumber: "0345778782",
                email: "",
                gender: "female",
                dateOfBirth: 12,
                cnic: 42401 - 4,
                address: "",
                githubUrl: "",
                numberOfStudents: 1,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "",
                qualification: "",
                university: "",
                faculty: "",
                yearOfPassedOut: 1,
                haseExperience: "false",
                NumOfYearsOfExperience: 0,
                meritalState: "single",
                skills: [],
                salary: 0000,
                hasAnyOtherJob: "false",
                OtherJob: "",
                certification: [],
                awards: [],
            }, {
                embassader2: "",
                position: "embassader",
                contactNumber: "0345778782",
                email: "",
                gender: "male",
                dateOfBirth: 12,
                cnic: 42401 - 4,
                address: "",
                githubUrl: "",
                numberOfStudents: 1,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "",
                qualification: "",
                university: "",
                faculty: "",
                yearOfPassedOut: 1,
                haseExperience: "false",
                NumOfYearsOfExperience: 0,
                meritalState: "single",
                skills: [],
                salary: 0000,
                hasAnyOtherJob: "false",
                OtherJob: "",
                certification: [],
                awards: [],

            }, {
                embassader1: "",
                position: "embassader",
                contactNumber: "0345778782",
                email: "",
                dateOfBirth: 12,
                cnic: 42401 - 4,
                gender: "female",
                address: "",
                githubUrl: "",
                numberOfStudents: 1,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "",
                qualification: "",
                university: "",
                faculty: "",
                yearOfPassedOut: 1,
                haseExperience: "false",
                NumOfYearsOfExperience: 0,
                meritalState: "single",
                skills: [],
                salary: 0000,
                hasAnyOtherJob: "false",
                OtherJob: "",
                certification: [],
                awards: [],
            }

        ],


    },
    schedule: {
        timings: 2 - 6,
        numberOfhours: 4,
        days: ["tuesday","thursday", "saturday"],
        webDevClasseTimingsForGroupA: 2 - 4,
        practiceHoursForGropA: 4 - 6,
        webDevClasseTimingsForGroupB: 4 - 6,
        practiceHoursForGropB: 2 - 4,
        numbersOfMentorMeetupClassesPorMonth:1,
        daysOfMentorMeetupClasses:"saturday"

    },
    students: {
        numberOfStudents: 100,
        NumberOfFemaleStudents: 70,
        NumberOfMAleStudents: 30,
        numberOfGroupsOfStudents: 2,
        numberOfStudentsPerGroup: 50,
        namesOfStudentsOfGroupA: ["nazia", "khadija", "mahnoor", "nusheen","aliraza","talat" ],
        namesOfStudentsOfGroupB: ["fatima", "kaiser", "kokab","faizan", "somia", "armia"],
        discriptionOfStudentsOfGroupA: [{
            student1: "nazia",
            fullName: "Nazia Jaffer",
            contactNumber: 0345 - 6897823,
            email: "naziajaffer34@gmail.com",
            address: "yaqoob shah basti manghopir karachi",
            githubUrl: "naziaj",
            dateOfBirth: 2 - 3 - 1999,
            cnicNumber: 42401 - 4,
            gender: "female",
            meritalState: "",
            qualification: "b-com",
            nameOfinstitude: "",
            yearOfPassedOut: 2,
            fatheroccupation: "",
            monthlyIncome: 30000,
            numberOfSiblings: 6,
            numberOfBrothers: 3,
            numberOfsisters: 3,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmaetPhone: "true",
                hasWebdevbackground: "",
                Occupatioin: "",
                addressOfPlaceOfWork: "",
                daysOFWorking: [],
                isComingdirectFromWorkPlace: "",
                distancefromWorkPlaceToInstitudeinKm: "",
                distancefromhomeToInstitudeinKm: "",
                salary: 5,
                meanOFTransport: "",
            },
            skills:[],
            intrests:[]
        },{
            student2:"",
            fullName:"",
            contactNumber:0345-6897823,
            email:"@gmail.com",
            address:"",
            githubUrl:"",
            dateOfBirth:2-3-1999,
            gender:"",
            qualification:"",
            nameOfCollege:"",
            yearOfPassedOut: 2,
            fatheroccupation: "",
            monthlyIncome: 30000,
            numberOfSiblings: 6,
            numberOfBrothers: 3,
            numberOfsisters: 3,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmaetPhone: "true",
                hasWebdevbackground: "",
                Occupatioin: "",
                addressOfPlaceOfWork: "",
                daysOFWorking: [],
                isComingdirectFromWorkPlace: "",
                distancefromWorkPlaceToInstitudeinKm: "",
                distancefromhomeToInstitudeinKm: "",
                salary: 5,
                meanOFTransport: "",
            },
            skills:[],
            intrests:[]
        }],
        discriptionsOfStudentsOfGroupB:[{
            student1:"",
            fullName:"",
            contactNumber:0345-6897823,
            email:"@gmail.com",
            address:"",
            githubUrl:"",
            dateOfBirth:2-3-1999,
            gender:"",
            qualification:"",
            nameOfCollege:"",
            yearOfPassedOut: 2,
            fatheroccupation: "",
            monthlyIncome: 30000,
            numberOfSiblings: 6,
            numberOfBrothers: 3,
            numberOfsisters: 3,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmaetPhone: "true",
                hasWebdevbackground: "",
                Occupatioin: "",
                addressOfPlaceOfWork: "",
                daysOFWorking: [],
                isComingdirectFromWorkPlace: "",
                distancefromWorkPlaceToInstitudeinKm: "",
                distancefromhomeToInstitudeinKm: "",
                salary: 5,
                meanOFTransport: "",
            },
            skills:[],
            intrests:[]
        },{
            student2:"",
            fullName:"",
            contactNumber:0345-6897823,
            email:"@gmail.com",
            address:"",
            githubUrl:"",
            dateOfBirth:2-3-1999,
            gender:"",
            qualification:"",
            nameOfCollege:"",
            yearOfPassedOut: 2,
            fatheroccupation: "",
            monthlyIncome: 30000,
            numberOfSiblings: 6,
            numberOfBrothers: 3,
            numberOfsisters: 3,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmaetPhone: "true",
                hasWebdevbackground: "",
                Occupatioin: "",
                addressOfPlaceOfWork: "",
                daysOFWorking: [],
                isComingdirectFromWorkPlace: "",
                distancefromWorkPlaceToInstitudeinKm: "",
                distancefromhomeToInstitudeinKm: "",
                salary: 5,
                meanOFTransport: "",
            },
            skills:[],
            intrests:[]
        }]

    },
    extraClasses:{

    },
    events:{
    
    },
    expenses:{

    },
    certifications:{

    },
    lifeSkillClasses:{

    },






}







