let techKaro = {
    about: {
        programName: "Tech Karo",
        discription: "web-dev course",
        about: "TechKaro is an 8 months' Web Development Course, offered by CIRCLE Women Pakistan and sponsored by Engro Vopak. The course is aimed at talented but underserved youth of Pakistan. Our goal is to empower women in technology and help them generate income through their Web Developement skills.",
        duration: "8 months",
        fees: 500,
        leadBy: "Circle",
        founder: "Miss Sadaf Abid",
        instructor: "Miss Sarah Ahmed",
        courses: ["html", "CSS", "javascript"],
        institude: "Usman institude of technology",
        location: "ST-13 Abul Hasan Isphahani Rd, Block 7 Gulshan-e-Iqbal, Karachi, Karachi City",
        contact: "021-453768",
        email: "techkaro67@gmail.com",
        website: "www.techkaro.com",
        numberOfTeacher: 1,
        numberOfStudents: 100,
        NumberOfEmployess: 20,
        sponcers: {
            sponser1: "Engro Vopak",
            aboutSponser: "",
            email: "engrovopak@.org",
            contactNumebr: 021 - 3457,
            loctaion: "",
            amount: "500000",
        }
    },
    facilities: {
        transport: {
            isProvidingTransport: "true",
            collabotationWith: "Creem",
            discountPerRide: "50%",
        },
        labs: {
            isProvidingLAbs: "true",
            location: "Usman Institude",
            numberOfLAbs: 4,
            names: ["cl1", "cl2", "cl4", "fyp lab"],
            isProvidingAirConditionerFacilities: "true",
            isProvidingCleanEnvironment: "true",
            numbersOfComputersPerLab: 80,
            isProvidingInternet: "true",
            isProvidingLAbAssistant: "true",
            numberOfLAbAssistantPerLAb: 2,
            discriptionOfLAbAssistants: [{
                labAssistant1: "ali",
                gender: "male",
                contact: 0335 - 6789387,
                email: "aliraza67@gmail.com",
                numOfhoursOfAvailibility: 4,
            }, {
                labAssistant2: "faizan",
                gender: "male",
                contact: 0335 - 67267927,
                email: "faizankahn20@gmail.com",
                numOfhoursOfAvailibility: 4,
            }],
            isprovidingChairs: "true",
            numberOfChairsPerClass: 70,
            isprovidingTables: "true",
            numberOfChairsPerClass: 30,
        },
        notebooks: {
            isProvidingNotebooks: "true",
            givenBy: "Engro Vopek",
            numberOfNotebooksPerStudents: 1,
        }


    },
    employes: {
        employ1: "teacher",
        numberOfTeacher: 1,
        discriptionOfTeacher: {
            name: "Sarah Ahmed",
            contactNumber: "0345778912",
            email: "sarah-ahmed11@gmail.com",
            dateOfBirth: 12 - 5 - 1995,
            cnic: 42401 - 3234768,
            address: "house no.34 shahrahe faisal karachi",
            githubUrl: "sarahsj.ghithub.com",
            qualification: "Mscs",
            university: "NEd University",
            faculty: "omputer",
            yearOfPassedOut: 2014,
            haseExperience: "true",
            NumOfYearsOfExperience: 2,
            meritalState: "single",
            skills: ["web developer", "teaching"],
            salary: 900000,
            hasAnyOtherJob: "true",
            OtherJob: "Free Launcer",
            certification: ["free code camp", "exellent web developer"],
            awards: ["abc", "def", "xyz"],
        },
        employ2: "Program Manager",
        numberOfProgramManagers: 2,
        discriptionsOfProgramManagers: [
            {
                programManager1: "Tuba Mohsin",
                position: "manager",
                contactNumber: "034567812",
                email: "tubamohsin@gmail.com",
                dateOfBirth: 4 - 6 - 1993,
                cnic: 42401 - 47837528,
                address: "sjkdhflkhbnjvkjd",
                qualification: "Mscs",
                university: "NED University",
                faculty: "Computer Science",
                yearOfPassedOut: 1994,
                haseExperience: "true",
                NumOfYearsOfExperience: 1,
                meritalState: "single",
                skills: ["management", "web developer", "communication"],
                salary: 860000,
                hasAnyOtherJob: "true",
                OtherJob: "true",
                certification: ["free code camp", "management certification"],
                awards: ["best manager", "developer of the year"],
            }, {
                programManager2: "Mashaal",
                position: "Manager",
                contactNumber: "0345778912",
                email: "mashalkhan65@gmail.com",
                dateOfBirth: 12 - 8 - 1993,
                cnic: 42401 - 4438769845,
                address: "lkjdbvsdgikhnkjb",
                qualification: "PHD",
                university: "Karachi university",
                faculty: "Management",
                yearOfPassedOut: 2013,
                haseExperience: "true",
                NumOfYearsOfExperience: 5,
                meritalState: "single",
                skills: ["mangement", "communication", "leadership"],
                salary: 230000,
                hasAnyOtherJob: "true",
                OtherJob: "true",
                certification: ["dsfjg", "cguyg", "yucgvueg"],
                awards: [""],
            },

        ],
        employ3: "embassaders",
        numberOfEmbassaders: 10,
        discriptionsOfEmbassadors: [
            {
                embassader1: "miss khairun nisa",
                position: "embassader",
                contactNumber: "0345778782",
                email: "kahirun-nisa45@gmail.com",
                gender: "female",
                dateOfBirth: 3 - 8 - 1995,
                cnic: 42401 - 4378985,
                address: "house no.68 nagan  chorngi karachi",
                githubUrl: "kahirunnisa45.ghithub.com",
                numberOfStudents: 19,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "false",
                qualification: "Bachelor in computer",
                university: "karachi",
                faculty: "computer",
                yearOfPassedOut: 1,
                haseExperience: "false",
                NumOfYearsOfExperience: 0,
                meritalState: "single",
                skills: ["web developer", "communicat", "leadership"],
                salary: 5000,
                hasAnyOtherJob: "false",
                OtherJob: "",
                certification: "free code camp",
                awards: ["null"],
                isPreviuosAtudentOfTechkaro: "false"
            }, {
                embassader2: "miss arsala",
                position: "embassader",
                contactNumber: "0345778782",
                email: "arslaali5@gmail.com",
                gender: "female",
                dateOfBirth: 24 - 7 - 1995,
                cnic: 42401 - 43688985,
                address: "house no.78 north nzimabad karachi",
                githubUrl: "arslanali.ghithub.com",
                numberOfStudents: 19,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "false",
                qualification: "master in computer",
                university: "karachi",
                faculty: "computer",
                yearOfPassedOut: 2017,
                haseExperience: "true",
                NumOfYearsOfExperience: 2016,
                meritalState: "single",
                skills: ["web developer", "communicat", "leadership"],
                salary: 7000,
                hasAnyOtherJob: "true",
                OtherJob: "teaching",
                certification: "free code camp",
                awards: ["null"],
                isPreviuosAtudentOfTechkaro: "false"
            }, {
                embassader3: "sir ali",
                position: "embassader",
                contactNumber: "03457786572",
                email: "alibahdur@gmail.com",
                gender: "male",
                dateOfBirth: 3 - 8 - 1996,
                cnic: 42401 - 4378985,
                address: "house no.8 nazimabad karachi",
                githubUrl: "kahirunnisa45.ghithub.com",
                numberOfStudents: 10,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "true",
                qualification: "Bachelor in computer",
                university: "karachi",
                faculty: "computer science",
                yearOfPassedOut: 2016,
                haseExperience: "false",
                NumOfYearsOfExperience: 0,
                meritalState: "single",
                skills: ["web developer", "leadership"],
                salary: 10000,
                hasAnyOtherJob: "false",
                OtherJob: "null",
                certification: "free code camp",
                awards: ["null"],
                isPreviuosAtudentOfTechkaro: "false"
            }, {
                embassader4: "miss rabia",
                position: "embassader",
                contactNumber: "0345772382",
                email: "rabiakhan-45@gmail.com",
                gender: "female",
                dateOfBirth: 3 - 8 - 1995,
                cnic: 42401 - 4372385,
                address: "house no.68 nagan  chorngi karachi",
                githubUrl: "rabiaanuum42.ghithub.com",
                numberOfStudents: 12,
                hasComputer: "true",
                hasInternert: "true",
                isProvidedTransportFacility: "true",
                qualification: "Bachelor in computer",
                university: "karachi university",
                faculty: "computer",
                yearOfPassedOut: 2014,
                haseExperience: "true",
                NumOfYearsOfExperience: 1,
                meritalState: "single",
                skills: ["web developer", "communication", "leadership"],
                salary: 5000,
                hasAnyOtherJob: "false",
                OtherJob: "null",
                certification: ["free code camp", "tech karo html", "techkaro css", "tech karro javascript"],
                awards: ["null"],
                isPreviuosAtudentOfTechkaro: "true",
                batch: 2018,
                isSucceedStudent: "true"
            }

        ],


    },
    schedule: {
        timings: 2 - 6,
        numberOfhours: 4,
        days: ["tuesday", "thursday", "saturday"],
        webDevClasseTimingsForGroupA: 2 - 4,
        practiceHoursForGropA: 4 - 6,
        webDevClasseTimingsForGroupB: 4 - 6,
        practiceHoursForGropB: 2 - 4,
        numbersOfMentorMeetupClassesPorMonth: 1,
        daysOfMentorMeetupClasses: "saturday"

    },
    students: {
        numberOfStudents: 100,
        NumberOfFemaleStudents: 70,
        NumberOfMAleStudents: 30,
        numberOfGroupsOfStudents: 2,
        numberOfStudentsPerGroup: 50,
        namesOfStudentsOfGroupA: ["nazia", "khadija", "mahnoor", "nusheen", "aliraza", "talat"],
        namesOfStudentsOfGroupB: ["fatima", "kaiser", "kokab", "faizan", "somia", "armia"],
        discriptionsOfStudentsOfGroupA: [{
            student1: "nazia",
            fullName: "Nazia Jaffer",
            contactNumber: 0345 - 6897823,
            email: "naziajaffer34@gmail.com",
            address: "yaqoob shah basti manghopir karachi",
            githubUrl: "naziaj",
            dateOfBirth: 2 - 3 - 1999,
            cnicNumber: 42401 - 4,
            gender: "female",
            meritalState: "single",
            qualification: "b-com",
            nameOfinstitude: "degree college of women",
            yearOfPassedOut: 2018,
            fatheroccupation: "employ",
            monthlyIncome: 30000,
            numberOfSiblings: 6,
            numberOfBrothers: 3,
            numberOfsisters: 3,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmartPhone: "true",
                hasWebdevbackground: "false",
                hasAnyOtherJob: "true",
                jobName: "teaching",
                addressOfPlaceOfWork: "nipa chorangi karachi",
                daysOFWorking: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
                isComingdirectFromWorkPlace: "true",
                distancefromWorkPlaceToInstitudeinKm: "2km",
                distancefromhomeToInstitudeinKm: "3km",
                salary: 5000,
                meanOFTransport: "bus",
            },
            skills: ["english languege", "leadership"],
            intrests: ["coding", "learing", "java script"],
            anyCertification: ["soft skill", "language", "CIT"]
        }, {
            student2: "FATIMA",
            fullName: "fatima aman",
            contactNumber: 0345 - 687823,
            email: "fatimaaman@gmail.com",
            address: "yaqoob shah basti manghopir karachi",
            githubUrl: "fatimaaman123",
            dateOfBirth: 18 - 3 - 2000,
            cnicNumber: 42401 - 46477456,
            gender: "female",
            meritalState: "single",
            qualification: "Bsc",
            nameOfinstitude: "fadral urdu university",
            isPassedOut: "false",
            yearOfPassedOut: 0,
            fatheroccupation: "tailor",
            monthlyIncome: 30000,
            numberOfSiblings: 5,
            numberOfBrothers: 0,
            numberOfsisters: 5,
            requirements: {
                hasComputer: "true",
                hasInternert: "ture",
                hasSmartPhone: "true",
                hasWebdevBackground: "false",
                hasAnyOtherJob: "false",
                jobName: "null",
                addressOfuniversity: "gulshan iqbal",
                daysOAttrndingUniversity: ["monday", "tuesday", "wednesday", "thursday", "friday",],
                isComingdirectFromUnivesity: "true",
                distancefromUniversityToInstitudeinKm: "2km",
                distancefromhomeToInstitudeinKm: "3km",
                salary: 0,
                meanOFTransport: "bus",
            },
            skills: ["english languege", "leadership"],
            intrests: ["coding", "learing", "java script"],
            anyCertification: ["soft skill", "language", "CIT"]
        }, {
            student3: "armia",
            fullName: "armia mohsin",
            contactNumber: 0357 - 682343,
            email: "armiamohsin@gmail.com",
            address: "yaqoob shah basti manghopir karachi",
            githubUrl: "armiaj",
            dateOfBirth: 23 - 3 - 1999,
            cnicNumber: 42401 - 455687,
            gender: "female",
            meritalState: "single",
            qualification: "BA",
            nameOfinstitude: "degree college of women",
            yearOfPassedOut: 2018,
            fatheroccupation: "employ",
            monthlyIncome: 30000,
            numberOfSiblings: 7,
            numberOfBrothers: 3,
            numberOfsisters: 34,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmartPhone: "true",
                hasWebdevbackground: "false",
                hasAnyOtherJob: "true",
                jobName: "teaching",
                addressOfPlaceOfWork: "nipa chorangi karachi",
                daysOFWorking: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
                isComingdirectFromWorkPlace: "true",
                distancefromWorkPlaceToInstitudeinKm: "2km",
                distancefromhomeToInstitudeinKm: "3km",
                salary: 5000,
                meanOFTransport: "bus",
            },
            skills: ["english languege", "leadership"],
            intrests: ["coding", "learing", "java script"],
            anyCertification: ["soft skill", "language", "CIT"]
        }],
        discriptionsOfStudentsOfGroupB: [{
            student1: "kainat",
            fullName: "kaiat naz",
            contactNumber: 0357 - 4797200,
            email: "kainat-jaz@gmail.com",
            address: "karimabad karachi",
            githubUrl: "kainatnaz.ghithub.com",
            dateOfBirth: 23 - 3 - 1999,
            cnicNumber: 42401 - 45568776,
            gender: "female",
            meritalState: "single",
            qualification: "BA",
            nameOfinstitude: "degree college of women",
            yearOfPassedOut: 2017,
            fatheroccupation: "officer",
            monthlyIncome: 40000,
            numberOfSiblings: 3,
            numberOfBrothers: 1,
            numberOfsisters: 2,
            requirements: {
                hascomputer: "true",
                hasInternert: "ture",
                hasSmartPhone: "true",
                hasWebdevbackground: "true",
                hasAnyOtherJob: "true",
                jobName: "teaching",
                addressOfPlaceOfWork: "nipa chorangi karachi",
                daysOFWorking: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
                isComingdirectFromWorkPlace: "true",
                distancefromWorkPlaceToInstitudeinKm: "1km",
                distancefromhomeToInstitudeinKm: "4km",
                salary: 8000,
                meanOFTransport: ["bus", "chinchi", "rikshaw"],
            },
            skills: ["english languege", "leadership", ""],
            intrests: ["coding", "learing", "watching movies"],
            anyCertification: ["language", "CIT"]
        }, {
            student2: "shayan",
            fullName: "shayanejaz45@gmail.com",
            contactNumber: "0333-68533",
            email: "shayanejaz45@gmail.com",
            address: "block m north nazimabd karachi",
            githubUrl: "shayankhan.github.com",
            dateOfBirth: 18 - 3 - 2000,
            cnicNumber: 42401 - 46477456,
            gender: "male",
            meritalState: "single",
            qualification: "Bs",
            nameOfinstitude: "karachi university",
            isPassedOut: "false",
            yearOfPassedOut: 0,
            fatheroccupation: "bussinessman",
            monthlyIncome: 600000,
            numberOfSiblings: 2,
            numberOfBrothers: 0,
            numberOfsisters: 1,
            requirements: {
                hasComputer: "true",
                hasInternert: "ture",
                hasSmartPhone: "true",
                hasWebdevBackground: "false",
                hasAnyOtherJob: "false",
                jobName: "null",
                addressOfuniversity: "gulshan iqbal",
                daysOAttrndingUniversity: ["monday", "tuesday", "wednesday", "thursday", "friday",],
                isComingdirectFromUnivesity: "true",
                distancefromUniversityToInstitudeinKm: "500m",
                distancefromhomeToInstitudeinKm: "700m",
                salary: 0,
                meanOFTransport: ["bus", "bike"],
            },
            skills: ["art", "coding"],
            intrests: ["coding", "drawing", "graphics"],
            anyCertification: ["soft skill", "graphics", "CIT"]
        }, {
            student2: "somia",
            fullName: "somi ansari",
            contactNumber: 0345 - 687823,
            email: "somia-ansari@gmail.com",
            address: "northkarachi",
            githubUrl: "somia ansri",
            dateOfBirth: 18 - 3 - 2000,
            cnicNumber: 42401 - 46477456,
            gender: "female",
            meritalState: "single",
            qualification: "Bsc",
            nameOfinstitude: "karachi university",
            isPassedOut: "true",
            yearOfPassedOut: 2018,
            fatheroccupation: "employ",
            monthlyIncome: 30000,
            numberOfSiblings: 4,
            numberOfBrothers: 3,
            numberOfsisters: 0,
            requirements: {
                hasComputer: "true",
                hasInternert: "ture",
                hasSmartPhone: "true",
                hasWebdevBackground: "false",
                hasAnyOtherJob: "false",
                jobName: "null",
                addressOfuniversity: "gulshan iqbal",
                daysOAttrndingUniversity: ["monday", "tuesday", "wednesday", "thursday", "friday",],
                isComingdirectFromUnivesity: "true",
                distancefromUniversityToInstitudeinKm: "400m",
                distancefromhomeToInstitudeinKm: "1km",
                salary: 0,
                meansOFTransport: ["bus", "rikshaw"],
            },
            skills: ["english languege", "leadership"],
            intrests: ["coding", "learing", "graphics"],
            anyCertification: ["soft skill", "language", "CIT"]
        }]

    },
    extraClasses: {
        timings: 6 - 7,
        days: ["tuesday", "thursday", "saturday"],
        numberOfStudents: 40,
        NumberOfFemaleStudents: 30,
        NumberOfmaleStudents: 10,
        topics: ["html", "css", "javascript"],
        labs: ["cl1", "cl2"],
        isAttendenceCompulsory: "fales",
        isCareemCodeAvailable: "true",

    },
    events: {
        mentorMeetup: {
            manager1: "mIss tuba",
            manager2: "MIss Mashaal",
            numberOfMentors: 15,
            mentors: {
                comingFromOrganisations: [{
                    name: "engro vopak",
                    noOfMentorsProviding: 5,
                }, {
                    name: "susta tiket",
                    noOfMentorsProviding: 4,
                }, {
                    name: "parsa tower",
                    noOfMentorsProviding: 2,
                }
                ]

            },
            numberOfStudentsForEachMentor: 15,
            numberOfGroupsOfStudents: 8,
            locations: ["cl1", "auditorium"],

        },
        EidMillanParty: {
            managedBy: ["miss tuba", "miss mishaal"],
            cheifeGuests: ["miss Sadaf", "Sir Tahir"],
            locaton: "casbianca benquet",
            menu: {
                dishes: ["biryani", "qorma", "kabab",],
                deserts: ["banana dsert", "mango desrt"],
                drinks: ["coca cola", "dew", "7up"],
            },
            numberOfStudentsAttending: 80,
            totalNumbeOfPersons: 150,
            sponceredBy: "engro vopak",
        },
        convocationEvent: {
            managedBy: ["miss tuba", "miss mishaal", "miss Sarah"],
            cheifeGuests: ["miss Sadaf", "Sir Tahir", "ceo of engro"],
            locaton: "lalazar benquet",
            numberOfStudentsAttending: 100,
            totalNumbeOfPersons: 200,
            sponceredBy: "engro vopak",
        }

    },
    expenses: {
        forLocations: 40000,
        forTransport: 500000,
        forComputers: 76000,
        forAirConditioners: 2000,
        forEvents: 459000,
        forlabs: 2800,
    },
    certifications: {
        certificate1: "free code camp",
        certificatesOfFreeCodeCamp: ["responsive web desighn", "java script"],
        certificate2: "tech karo",
        certificatesOfTechkaro: ["css", "html", "java script"],
    },
    lifeSkillClasses: {
        managedBy: ["miss tuba ", "miss sarah"],
        conductBy: {
            nameOfOrganisation: "Amwaj",
            email: "amwaj-schoolofleadership2.gmail",
            numberOfSpeakers: 4,
            numberOfMaleSpeakers: 3,
            numberOffeMaleSpeakers: 1,
        },
        locations: ["cl1", "cl4"],
        numberOfStudentsAttending: 100,
        numberOfEmbassadersAttending: 10,
        isAttendenceCompulsory: "true",
        isCareemCodeAreAvailable: "true",
        days: "saturday",
    },






}





